### ISSUE TITLE
Pistons move nodes into protected areas

### ISSUE THREAD

**Issue by volkj** [minetest-mods/mesecons#281]
Tested with Minetest 0.4.14 vanilla with Landrush and mesecons both git-cloned

After i defined a protected area with Landrush (it should work with other protection mod) i was able, with a user different from the protected area owner, to push nodes inside it to move its contents. 

Even if the contents stopped at the protected area limit, the protected area has contents moved and external nodes pushed inside, this may lead to griefs.

**Comment by HybridDog** [comment]
@volkj currently the player name is not given, but the code can be amended:
"When the piston is placed, the name of the player is saved to it and when the piston pushes, it passes the placer's name to mvps for the protection test. To support older pistons, the test is skipped if the placer name is not available."

**Comment by jhcole** [comment]
Sticky pistons can also be used to pull nodes out of a protected area. In fact, I even once built a self propelled mesecon train that can plow right through other players protected areas. This is an important issue to me.

> To support older pistons, the test is skipped if the placer name is not available.

I'm happy with this as long as we can be sure _new_ pistons will have a placer name, and respect protection.

**Comment by LoneWolfHT** [comment]
This is still a problem. And the same seems to be true for movestones too

**Comment by numberZero** [comment]
Sure. See discussion in #312.

**Comment by LoneWolfHT** [comment]
> Sure. See discussion in #312.

Any chance it'll be un-abandoned? \:P

**Comment by numberZero** [comment]
Possible. But the “security vs. backward compatibility” problem needs to be solved. Here are my suggestions:
1. For any new piston, record the placer. If the placer can’t be determined, record sentinel value like `$unknown` instead (as `$` can’t appear in a player name IIRC)
2. If the placer is recorded, use it to test for protection. Sentinel is usable as well, preventing acting in *any* protected area.
3. Otherwise, the piston is either old or placed by world-edit-like tool. The behavior should be configurable for these.

**Comment by LoneWolfHT** [comment]
Sounds like a good idea to me
