### ISSUE TITLE
Admin cannot remove protected commandblocks

### ISSUE THREAD

**Issue by ZettaScript** [minetest-mods/mesecons#514]
Commandblocks placed by any user cannot be digged by an admin who as all the privileges. (the block disappears and reappears instantly)

A user with privilege `protection_bypass` (or something else) should be able to remove commandblocks.

Bug found with minetest-server 5.2.0, Debian Buster.

**Comment by BuckarooBanzay** [comment]
i had the same problem, the cause is here:

https://github.com/minetest-mods/mesecons/blob/75bd1e8be6e9dbcfb722790087a9ed30046d8136/mesecons_commandblock/init.lua#L174-L178

This does not check if the digger has the `protection_bypass` privilege so the node can't be removed as a non-owner with normal tools.
A workaround would be to use `worldedit` though :wink:
