### ISSUE TITLE
output of print() goes to the server log. 

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/mesecons#626]
this partially intersects w/ #388, but i don't think it's entirely a dupe.

on public servers, having the output of `print()` go to the server log is worse than useless. players cannot see it, and it can clog up the log w/ a lot of spurious, unfilterable garbage. 

at the very least, there should be an option to disable the output that servers can enable. if others agree on that, i can create a PR.

**Comment by Desour** [comment]
:+1: It's bad that `print` writes into log and server terminal, even on public servers.

Suggestion: Add a setting (default `false`) that makes it a no-op. (Setting, and not `minetest.is_singleplayer()`, because users otherwise get confused on why their luacontroller doesn't work on their (local) server.)

**Comment by TurkeyMcMac** [comment]
Maybe `print` could call a separate function `write_to_terminal` after formatting its arguments. `write_to_terminal` would be a no-op by default, but it could be overriden by the LuaController code to write to a digiline device or something.
