### ISSUE TITLE
Add `math.eval` to evaluate strings as math expressions

### ISSUE THREAD

**Issue by Bituvo** [minetest-mods/mesecons#634]
I think LUACs could benefit from having a function added to them that would take a string ("5 + (2.5 - 3) / -4") and evaluate it as if it were a mathematical expression. Here is some code I wrote that might work:

```lua
local function evaluate(expression)
    -- Make sure expression only contains valid characters
   if string.match(expression, "^[-.\\+*\\/()%d ]+$") then
      return loadstring("return " .. expression)()

   else
      debug.sethook()
      error("Expression contained invalid character(s)")
   end
end
```

And then we could add the line `eval = evaluate` to `env.math`.

I would make a PR but I tried doing this myself and the function wouldn't return a value in the LUAC for whatever reason. I'm not particularly experienced in its ways.

I am aware that the code I wrote may be prone to some things, but that's what the community is for :)

**Comment by Desour** [comment]
Seems a bit too special, imho. Could be done optionally with #428.

You probably need this to handle user input from some digiline device, I guess, right? Or what other use-cases do you have?

I'd suggest you make a separate digiline device that does exactly this thing. Or use a custom mesecons fork. Otherwise, you'll probably wait to death.

**Comment by Bituvo** [comment]
Yeah, I guess I could just make a separate digilines device... closing.
