### ISSUE TITLE
add effector with capability to break nodes

### ISSUE THREAD

**Issue by lolbinarycat** [minetest-mods/mesecons#664]
brought up in #543, this would greatly increase the types of automation possible with mesecons.

unsure if this already exists in another mod.

the node would have a single inventory slot with a tool.

when given power, it would calculate mining time for the node it was facing based on the tool it contained.

after the calculated amount of time had passed, calls `minetest.dig_node` and adds wear to the contained tool.

the item is dropped where the node previously was.

**Comment by Desour** [comment]
Apart from the dig time, the node breaker in pipeworks already does this.

This feature is more work to implement properly than you might think, because you need a fake player for `on_dig` callbacks and similar.

(Also mesecons currently doesn't do anything with items, so it wouldn't really fit in. Disclaimer: That's just my opinion. I'm not a maintainer.)

**Comment by lolbinarycat** [comment]
thanks! that basically answers my question.

closing this as out of scope/covered by other mods.
